### ISSUE TITLE
Only supports voice and music mods atm

### ISSUE THREAD

**Issue by RegDuy** [legoandmars/SlimeModManager#1]
This only supports voice and music mods atm and not skin mods. I hope you fix this as not all mods are compatible with the current version of the loader.

**Comment by legoandmars** [comment]
I plan on working on a BepInEx-based skin loading mod, and once it's done it'll be added to the mod manager.

As far as I know the skin mods that exist right now are directly distributing sharedassets files, which are illegal to share and will not be supported on Slime Mod Manager
