### ISSUE TITLE
Can't Uncheck or Uninstall Mods

### ISSUE THREAD

**Issue by resoNathan** [legoandmars/SlimeModManager#7]
I cannot click on the checkboxes for any mods that I already have installed. If I try to update or install a single mod, it will instead update every mod I have ever owned through the manager. There also does not seem to be any option to uninstall. What this adds up to is me having to manually uninstall TophIsBlind.dll every time I want to update something, which is going to get quickly out of hand once I have more files in different locations that I want to disable. I've attached a screenshot so that you can see that the checkboxes are grayed out and there is nothing in the uninstall category.
![image](https://user-images.githubusercontent.com/24477941/136818416-784270c5-3b96-40ff-9165-3cec95540a88.png)

**Comment by legoandmars** [comment]
Fixed in [1.3.0](https://github.com/legoandmars/SlimeModManager/releases/tag/1.3.0)
